/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package starting;

import customerPackage.MusicBandModel;
import khakejaorestaurant.MyConnection;
import khakejaorestaurant.User;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import managerPackage.Manager;

/**
 *
 * @author sreyasborra
 */
public class MusicBand extends javax.swing.JFrame {
	
	private String band;

	/**
	 * Creates new form MusicBand
	 */
	public MusicBand() {
		initComponents();
	}
	
	public MusicBand(MusicBandModel band, String username) {
		initComponents();
		loadCurrentBandPersonData(username);
		txtUsername.setText(band.getUsername());
		txtPassword.setText(band.getPassword());
		txtPhoneNumber.setText(band.getPhoneNumber());
		txtBandName.setText(band.getName());
	}
	
	public void loadCurrentBandPersonData(String username) {
		PreparedStatement ps;
		ResultSet rs;
		String query = "SELECT * FROM music_band WHERE username=?;";
		try {
			ps = MyConnection.getConnection().prepareStatement(query);
			ps.setString(1, username);
			rs = ps.executeQuery();
			if (rs.next()) {
				String uname = rs.getString("username");
				String password = rs.getString("password");
				String mobile = rs.getString("phone_number");
				String band_name = rs.getString("band_name");
				String mobilePhone = rs.getString("phone_number");
				MusicBandModel band = new MusicBandModel();
				band.setName(band_name);
				band.setPassword(password);
				band.setPhoneNumber(mobilePhone);
				band.setUsername(username);
				
			} else {
				JOptionPane.showMessageDialog(null, "Fetched details of music band", null, JOptionPane.ERROR_MESSAGE);
			}
			
		} catch (SQLException ex) {
			System.out.println("fail");
			Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                pnl_background = new javax.swing.JPanel();
                pHeader = new javax.swing.JPanel();
                btnLogout = new javax.swing.JButton();
                lbLogo = new javax.swing.JLabel();
                txtPhoneNumber = new javax.swing.JTextField();
                txtUsername = new javax.swing.JTextField();
                txtBandName = new javax.swing.JTextField();
                txtPassword = new javax.swing.JPasswordField();
                jLabel1 = new javax.swing.JLabel();
                lblBandPhoneNum = new javax.swing.JLabel();
                lblBandUsername = new javax.swing.JLabel();
                lblBandPassword = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                pnl_background.setPreferredSize(new java.awt.Dimension(1216, 711));
                pnl_background.setLayout(null);

                pHeader.setBackground(new java.awt.Color(255, 213, 0));
                pHeader.setName("pHeader"); // NOI18N
                pHeader.setPreferredSize(new java.awt.Dimension(1062, 70));
                pHeader.setLayout(null);

                btnLogout.setBackground(new java.awt.Color(255, 213, 0));
                btnLogout.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
                btnLogout.setForeground(new java.awt.Color(127, 72, 101));
                btnLogout.setText("Log out");
                btnLogout.setToolTipText("");
                btnLogout.setBorder(null);
                btnLogout.setBorderPainted(false);
                btnLogout.setContentAreaFilled(false);
                btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnLogout.setName(""); // NOI18N
                btnLogout.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLogoutActionPerformed(evt);
                        }
                });
                pHeader.add(btnLogout);
                btnLogout.setBounds(670, 20, 101, 40);

                lbLogo.setBackground(new java.awt.Color(255, 255, 255));
                lbLogo.setFont(new java.awt.Font("Rockwell Condensed", 0, 52)); // NOI18N
                lbLogo.setForeground(new java.awt.Color(127, 72, 101));
                lbLogo.setText("Khake Jao");
                lbLogo.setToolTipText("");
                pHeader.add(lbLogo);
                lbLogo.setBounds(30, 10, 280, 62);

                pnl_background.add(pHeader);
                pHeader.setBounds(0, 0, 1220, 80);
                pnl_background.add(txtPhoneNumber);
                txtPhoneNumber.setBounds(260, 250, 250, 40);
                pnl_background.add(txtUsername);
                txtUsername.setBounds(260, 330, 250, 40);

                txtBandName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtBandNameActionPerformed(evt);
                        }
                });
                pnl_background.add(txtBandName);
                txtBandName.setBounds(260, 170, 250, 40);

                txtPassword.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtPasswordActionPerformed(evt);
                        }
                });
                pnl_background.add(txtPassword);
                txtPassword.setBounds(260, 410, 250, 40);

                jLabel1.setText("Band Name");
                pnl_background.add(jLabel1);
                jLabel1.setBounds(260, 150, 70, 16);

                lblBandPhoneNum.setText("Phone Number");
                pnl_background.add(lblBandPhoneNum);
                lblBandPhoneNum.setBounds(260, 230, 90, 16);

                lblBandUsername.setText("Username");
                pnl_background.add(lblBandUsername);
                lblBandUsername.setBounds(260, 310, 90, 16);

                lblBandPassword.setText("Password");
                pnl_background.add(lblBandPassword);
                lblBandPassword.setBounds(260, 390, 80, 16);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnl_background, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(336, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(pnl_background, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
	    HomepageForm homepage = new HomepageForm(true);
	    homepage.setVisible(true);
	    this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

        private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_txtPasswordActionPerformed

        private void txtBandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBandNameActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_txtBandNameActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MusicBand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MusicBand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MusicBand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MusicBand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MusicBand().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnLogout;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel lbLogo;
        private javax.swing.JLabel lblBandPassword;
        private javax.swing.JLabel lblBandPhoneNum;
        private javax.swing.JLabel lblBandUsername;
        public static javax.swing.JPanel pHeader;
        private javax.swing.JPanel pnl_background;
        private javax.swing.JTextField txtBandName;
        private javax.swing.JPasswordField txtPassword;
        private javax.swing.JTextField txtPhoneNumber;
        private javax.swing.JTextField txtUsername;
        // End of variables declaration//GEN-END:variables
}
