/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package starting;

import java.awt.Dialog.ModalityType;
import java.awt.Window;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author sreyasborra
 */
public class RolesLoginWindow extends javax.swing.JPanel {

	/**
	 * Creates new form RolesLoginWindow
	 */
	HomepageForm homeForm;

	public RolesLoginWindow() {
		initComponents();

	}

	public RolesLoginWindow(HomepageForm homeForm) {
		initComponents();
		this.homeForm = homeForm;

	}
	String type;

	/**
	 * Creates new form LoginRequest
	 */
	public void openLoginForm() {

		RoleLoginForm rolelogin = new RoleLoginForm(type, this.homeForm);
		JDialog dialog = new JDialog();
		dialog.add(rolelogin);
		dialog.setSize(500, 500);
		dialog.setModalityType(ModalityType.APPLICATION_MODAL);
		dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		dialog.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                btnManagerLoginReq = new javax.swing.JButton();
                btnCustomerLoginReq = new javax.swing.JButton();
                jPanel2 = new javax.swing.JPanel();
                lbLogo = new javax.swing.JLabel();
                btnHome = new javax.swing.JButton();
                btnCustomerLoginReq1 = new javax.swing.JButton();
                btnCustomerLoginReq2 = new javax.swing.JButton();
                btnOwnerLogin = new javax.swing.JButton();
                btnMusic = new javax.swing.JButton();

                btnManagerLoginReq.setFont(new java.awt.Font("Rockwell Condensed", 1, 28)); // NOI18N
                btnManagerLoginReq.setBorderPainted(false);
                btnManagerLoginReq.setContentAreaFilled(false);
                btnManagerLoginReq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnManagerLoginReq.setLabel("Manager Login");
                btnManagerLoginReq.setName(""); // NOI18N
                btnManagerLoginReq.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnManagerLoginReqActionPerformed(evt);
                        }
                });

                btnCustomerLoginReq.setBackground(new java.awt.Color(255, 213, 0));
                btnCustomerLoginReq.setFont(new java.awt.Font("Rockwell Condensed", 1, 28)); // NOI18N
                btnCustomerLoginReq.setText("Customer Login");
                btnCustomerLoginReq.setBorderPainted(false);
                btnCustomerLoginReq.setContentAreaFilled(false);
                btnCustomerLoginReq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnCustomerLoginReq.setName(""); // NOI18N
                btnCustomerLoginReq.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCustomerLoginReqActionPerformed(evt);
                        }
                });

                jPanel2.setBackground(new java.awt.Color(255, 0, 0));
                jPanel2.setPreferredSize(new java.awt.Dimension(396, 70));

                lbLogo.setBackground(new java.awt.Color(255, 255, 255));
                lbLogo.setFont(new java.awt.Font("AR CHRISTY", 1, 55)); // NOI18N
                lbLogo.setText("KhakeJao");
                lbLogo.setToolTipText("");

                btnHome.setText("Home");
                btnHome.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnHomeActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(264, 264, 264)
                                .addComponent(lbLogo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHome)
                                .addGap(164, 164, 164))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnHome)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                btnCustomerLoginReq1.setBackground(new java.awt.Color(255, 213, 0));
                btnCustomerLoginReq1.setFont(new java.awt.Font("Rockwell Condensed", 1, 28)); // NOI18N
                btnCustomerLoginReq1.setText("Waiter Login");
                btnCustomerLoginReq1.setBorderPainted(false);
                btnCustomerLoginReq1.setContentAreaFilled(false);
                btnCustomerLoginReq1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnCustomerLoginReq1.setName(""); // NOI18N
                btnCustomerLoginReq1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCustomerLoginReq1ActionPerformed(evt);
                        }
                });

                btnCustomerLoginReq2.setBackground(new java.awt.Color(255, 213, 0));
                btnCustomerLoginReq2.setFont(new java.awt.Font("Rockwell Condensed", 1, 28)); // NOI18N
                btnCustomerLoginReq2.setText("Chef Login");
                btnCustomerLoginReq2.setBorderPainted(false);
                btnCustomerLoginReq2.setContentAreaFilled(false);
                btnCustomerLoginReq2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnCustomerLoginReq2.setName(""); // NOI18N
                btnCustomerLoginReq2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCustomerLoginReq2ActionPerformed(evt);
                        }
                });

                btnOwnerLogin.setBackground(new java.awt.Color(255, 213, 0));
                btnOwnerLogin.setFont(new java.awt.Font("Rockwell Condensed", 1, 28)); // NOI18N
                btnOwnerLogin.setText("Owner Login");
                btnOwnerLogin.setBorderPainted(false);
                btnOwnerLogin.setContentAreaFilled(false);
                btnOwnerLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnOwnerLogin.setName(""); // NOI18N
                btnOwnerLogin.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnOwnerLoginActionPerformed(evt);
                        }
                });

                btnMusic.setBackground(new java.awt.Color(255, 213, 0));
                btnMusic.setFont(new java.awt.Font("Rockwell Condensed", 1, 28)); // NOI18N
                btnMusic.setText("Band Login");
                btnMusic.setBorderPainted(false);
                btnMusic.setContentAreaFilled(false);
                btnMusic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnMusic.setName(""); // NOI18N
                btnMusic.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnMusicActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1032, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnOwnerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnManagerLoginReq))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnCustomerLoginReq1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnCustomerLoginReq2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCustomerLoginReq, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 251, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCustomerLoginReq, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnOwnerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnManagerLoginReq))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCustomerLoginReq1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCustomerLoginReq2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(185, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

    private void btnManagerLoginReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerLoginReqActionPerformed
	    // TODO add your handling code here:
	    type = "Manager";
	    openLoginForm();
    }//GEN-LAST:event_btnManagerLoginReqActionPerformed

    private void btnCustomerLoginReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerLoginReqActionPerformed
	    // TODO add your handling code here:
	    type = "Customer";
	    openLoginForm();
    }//GEN-LAST:event_btnCustomerLoginReqActionPerformed

    private void btnCustomerLoginReq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerLoginReq1ActionPerformed
	    // TODO add your handling code here:

	    type = "Waitor";
	    openLoginForm();

    }//GEN-LAST:event_btnCustomerLoginReq1ActionPerformed

    private void btnCustomerLoginReq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerLoginReq2ActionPerformed
	    // TODO add your handling code here:

	    type = "Chef";
	    openLoginForm();
    }//GEN-LAST:event_btnCustomerLoginReq2ActionPerformed

    private void btnOwnerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOwnerLoginActionPerformed
		type = "Owner";
	    openLoginForm();	    // TODO add your handling code here:
    }//GEN-LAST:event_btnOwnerLoginActionPerformed

        private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
		// TODO add your handling code here:
		JComponent comp = (JComponent) evt.getSource();
		Window win = SwingUtilities.getWindowAncestor(comp);
		win.dispose();
		new HomepageForm().setVisible(true);

        }//GEN-LAST:event_btnHomeActionPerformed

        private void btnMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusicActionPerformed
                // TODO add your handling code here:
                type = "Music";
	    openLoginForm();
        }//GEN-LAST:event_btnMusicActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCustomerLoginReq;
        private javax.swing.JButton btnCustomerLoginReq1;
        private javax.swing.JButton btnCustomerLoginReq2;
        private javax.swing.JButton btnHome;
        private javax.swing.JButton btnManagerLoginReq;
        private javax.swing.JButton btnMusic;
        private javax.swing.JButton btnOwnerLogin;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JLabel lbLogo;
        // End of variables declaration//GEN-END:variables
}
